# Generated by Django 2.1.5 on 2019-02-12 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_data_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
