# Generated by Django 2.1.5 on 2019-03-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190302_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=100000),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
